export const Types = [
  ["STORE_TYPE", "Store Type"],
  ["STORE_NAME", "Store Name"],
  ["POS_ID", "POS ID"],
  ["PRODUCT_SN", "Product Serial Number"],
  ["CATEGORY", "Category"],
  ["PRODUCT", "Product"],
  ["COLOUR", "Colour"],
  ["SIZE", "Size"],
  ["QUANTITY", "Quantity"],
  ["DELIVERY_MODE", "Delivery Mode"],
  ["OPERATOR_ID", "Operator ID"],
  ["NAME", "Name"],
  ["PHONE", "Phone Number"],
  ["EMAIL", "Email"],
  ["COC", "Choice of communication"],
  ["ADDRESS", "Address"],
  ["PRODUCT_PRICE", "Product Price"],
  ["CGST", "CGST"],
  ["SGST", "SGST"],
  ["COUPON_CODE", "Coupon Code"],
  ["COUPON", "Coupon"],
  ["POINTS", "Points"],
  ["TOTAL", "Total"],
  ["PAYMENT_TYPE", "Payment Type"],
];
